### ISSUE TITLE
is_convertible_without_narrowing static assert is failing in some cases with GCC v7.3.1

### ISSUE THREAD

**Issue by lydia-at-amazon** [OpenCyphal/CETL#136]
When building with GCC v7.3.1, a number of static asserts in `type_traits_ext.hpp` and `test_type_traits_ext.cpp` fail:

```
include/cetl/type_traits_ext.hpp:125:1: error: static assertion failed: self-test failure
static_assert(is_convertible_without_narrowing<int, long long>::value, "self-test failure");
^~~~~~~~~~~~~

cetlvast/suites/unittest/test_type_traits_ext.cpp:53:1: error: static assertion failed
static_assert(is_convertible_without_narrowing<int, long long>::value, "");
^~~~~~~~~~~~~

cetlvast/suites/unittest/test_type_traits_ext.cpp:56:1: error: static assertion failed
static_assert(is_convertible_without_narrowing<float, long double>::value, "");
^~~~~~~~~~~~~

cetlvast/suites/unittest/test_type_traits_ext.cpp:71:1: error: static assertion failed
static_assert(!is_convertible_without_narrowing<long, foo_val>::value, "");
^~~~~~~~~~~~~

cetlvast/suites/unittest/test_type_traits_ext.cpp:73:1: error: static assertion failed
static_assert(!is_convertible_without_narrowing<long, foo_ref>::value, "");
^~~~~~~~~~~~~

cetlvast/suites/unittest/test_type_traits_ext.cpp:99:1: error: static assertion failed
static_assert(
^~~~~~~~~~~~~ 
```

**Comment by thirtytwobits** [comment]
Seeing this when compiling for Arduino as well. Do we think this a false positive?

**Comment by thirtytwobits** [comment]
This one is also found in GCC v8.3.1

**Comment by thirtytwobits** [comment]
Looks like changing type_traits_ext.hpp:123 from:

```
--     void_t<decltype(std::array<To, 1>{{{std::declval<From>()}}})>> : std::true_type
```
to
```
++ void_t<decltype(To{std::declval<From>()})>> : std::true_type
```
works fine. Not sure why we think the array conversion is needed?

**Comment by pavel-kirienko** [comment]
Your new form uses a stronger conversion than the original one. Per the C++ standard, the conversion should only succeed if it were valid in array initialization:

![Image](https://github.com/user-attachments/assets/5930211e-c4d1-448e-a3cf-b04bdc33b997)

Your new form will accept conversions that are not supposed to be accepted.

**Comment by thirtytwobits** [comment]
This is actually failing in gcc native cpp-14 builds using Ubuntu 12.3. I think the CI for CETL must be hosed or something.

```
[build] FAILED: suites/unittest/CMakeFiles/test_type_traits_ext__googletest_objlib.dir/Release/test_type_traits_ext.cpp.o 
[build] /usr/bin/g++ -DCETLVAST_COVERAGE -DCETL_ENABLE_DEBUG_ASSERT=0 -DCETL_VERSION=\"0.0.0\" -DLIBCXX_ENABLE_ASSERTIONS=0 -DCMAKE_INTDIR=\"Release\" -I/repo/cetlvast/include -I/repo/include -I/repo/cetlvast/build_external/o1heap/o1heap -isystem /repo/cetlvast/build_external/googletest/googletest/include -isystem /repo/cetlvast/build_external/googletest/googletest -isystem /repo/cetlvast/build_external/googletest/googlemock/include -isystem /repo/cetlvast/build_external/googletest/googlemock -O3 -DNDEBUG -std=c++14 -pedantic -Wall -Wextra -Werror -Wfloat-equal -Wconversion -Wunused-parameter -Wunused-variable -Wunused-value -Wcast-align -Wmissing-declarations -Wmissing-field-initializers -Wdouble-promotion -Wswitch-enum -Wtype-limits -Wno-error=array-bounds -O3 -fno-delete-null-pointer-checks -Wsign-conversion -Wsign-promo -Wold-style-cast -Wzero-as-null-pointer-constant -Wnon-virtual-dtor -Woverloaded-virtual -MD -MT suites/unittest/CMakeFiles/test_type_traits_ext__googletest_objlib.dir/Release/test_type_traits_ext.cpp.o -MF suites/unittest/CMakeFiles/test_type_traits_ext__googletest_objlib.dir/Release/test_type_traits_ext.cpp.o.d -o suites/unittest/CMakeFiles/test_type_traits_ext__googletest_objlib.dir/Release/test_type_traits_ext.cpp.o -c /repo/cetlvast/suites/unittest/test_type_traits_ext.cpp
[build] /repo/cetlvast/suites/unittest/test_type_traits_ext.cpp:104:90: error: static assertion failed
[build]   104 | static_assert(best_conversion_index_v<std::is_unsigned, long, char, long, unsigned long> == 2, "");
[build]       |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
[build] /repo/cetlvast/suites/unittest/test_type_traits_ext.cpp:104:90: note: the comparison reduces to ‘(18446744073709551615 == 2)’
```

**Comment by pavel-kirienko** [comment]
You mean Ubuntu 22.04?

**Comment by thirtytwobits** [comment]
This seems to work:
```
void_t<decltype(std::array<To, 1>{{std::forward<From>(std::declval<From>())}})>
```

https://godbolt.org/z/5sWjojK83

But then I run up against a new bug: GCC 7 things there is float/int comparison going on in the `best_conversion_index_v`.

**Comment by thirtytwobits** [comment]
After more hours of trying this is the best I can get to so far:

```cpp
#if defined(__GNUC__) and __GNUC__ <= 7

template <typename From, typename To>
struct is_convertible_without_narrowing<
    From, To,
    void_t<decltype(std::array<To, 1>{{std::forward<From>(std::declval<From>())}})>> : std::true_type
{
};

#else

template <typename From, typename To>
struct is_convertible_without_narrowing<
    From, To,
    void_t<decltype(std::array<To, 1>{{{std::forward<From>(std::declval<From>())}}})>> : std::true_type
{
};

```

This passes for everything except some of the struct conversions. Specifically, these two checks fail:

```
static_assert(!is_convertible_without_narrowing<long, foo_ref>::value, "");
static_assert(!is_convertible_without_narrowing<long, foo_val>::value, "");
```

As much as I hate to say it, I think we have to accept differnt/poor variant performance on gcc7 at this point. For example:

https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p0870r3.html#ch6.1

if you look at what QT has lived with until now it's actually slightly worse then the version I've proposed above.

**Comment by pavel-kirienko** [comment]
![Image](https://github.com/user-attachments/assets/b2045f94-f0aa-4e1c-a2d8-80aee05709a7)

**Comment by pavel-kirienko** [comment]
Is this still unaddressed?
